### ISSUE TITLE
Can't get post body content

### ISSUE THREAD

**Issue by qichunren** [cybercatalyst/shark#3]
When I send a POST request, server was not able to get post content.

I think maybe tcp socket readLine() function can't get content after '\r\n'
https://github.com/cybercatalyst/shark/blob/master/NetworkServiceThread.cpp#L81

**Comment by cybercatalyst** [comment]
Hey, shark is not very well tested and currently I am driving the development of qt-pods:
https://github.com/cybercatalyst/qt-pods

I think it is more important to get qt-pods stable, tested and promoted. After that I will extend shark as a Qt webserver component. I would ask you to be patient with this request, I will definately answer it and leave it open for reference, but I only have two hands :P 

Meanwhile, if you develop any Qt libs that you might find useful for others, I strongly encourage you to package them as a pod.

Happy hacking :)

**Comment by qichunren** [comment]
I send a PR, will you review it? Thank you. https://github.com/cybercatalyst/shark/pull/4

**Comment by cybercatalyst** [comment]
Thank you, merged :+1:
